version: "3"

services:
  redis:
    image: redis:4.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data

  db:
    image: postgres:12.2-alpine
    ports:
      - '5432:5432'
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
