name: Publish Docker image (develop)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.repository == 'pikokr/misskey'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.3.0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: pikokr/misskey
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/pikokr/misskey:latest
          labels: develop
      - name: Send update signal to kubernetes
        run: bash ./deploy/update.sh
        env:
          API_ENDPOINT: ${{ secrets.KUBE_API_ENDPOINT }}
          API_TOKEN: ${{ secrets.KUBE_API_TOKEN }}
